---
name: Font image

on:
  workflow_dispatch:

jobs:
  update:
    name: Update font image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dependencies
      - name: Update font image
        run: |
          python3 scripts/fontbuild.py -o /tmp/font.ttf
          bash scripts/fontimagegen.sh /tmp/font.ttf fontimage.png
      - name: Push the update to GitHub
        run: |
          git config user.email "saltcandy123@gmail.com"
          git config user.name "saltcandy123 (GitHub Actions)"
          git add fontimage.png
          if git commit -m "Update font image"; then
            git push origin
          else
            echo No change on fontimage.png
          fi
