name: Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build fonts and demo pages
    # Ubuntu 20.04 or later is required for python3-fontforge
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Lint glyph SVG files
      run: |
        python3 utils/clean_glyphs.py glyphs/
        git diff --numstat --exit-code
    - name: Install FontForge
      run: sudo apt-get install fontforge python3-fontforge
    - name: Build fonts
      run: python3 build_fonts.py --tag ${{ github.sha }}
    - name: Archive font-dist
      uses: actions/upload-artifact@v2
      with:
        name: font-dist
        path: font-dist
    - name: Build webapp
      run: |
        cd webapp
        yarn
        yarn run lint
        yarn run build
    - name: Archive webapp-dist
      uses: actions/upload-artifact@v2
      with:
        name: webapp-dist
        path: webapp-dist
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Super-Linter
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILTER_REGEX_EXCLUDE: .*/glyphs/.*|.*/webapp/.*\.(jsx?|tsx?)
