---
name: Verification

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-dist:
    name: Build font
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dependencies
      - name: Check glyph SVG files
        run: |
          python3 scripts/glyphclean.py glyphs/
          git diff --numstat --exit-code
      - name: Build dist
        run: python3 scripts/distbuild.py 0.0.0
      - name: Archive dist
        uses: actions/upload-artifact@v3
        with:
          path: dist
          name: dist
  fontbakery:
    name: Check with Font Bakery
    needs: build-dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Install Font Bakery
        run: python3 -m pip install fontbakery
      - name: Run Font Bakery
        run: |
          fontbakery check-universal \
            -x com.google.fonts/check/monospace \
            dist/npm-package/saltcandy123font-Regular.ttf
  super-linter:
    name: Check with Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*/glyphs/.*
